### ISSUE TITLE
Wrong default_client_id

### ISSUE THREAD

**Issue by cgascons** [dandar3/dandar3.github.io#1]
Hi!

First of all, thank you very much for such useful tool you got here, saved us a lot of time!
I just wanted to point out that the `default_client_id` according to this [link](https://developers.google.com/android/guides/google-services-plugin) should get the `client_type=3` value instead of the first one. 

Just wanted to let you know in case it's an easy fix on your end, again thanks!

**Comment by dandar3** [comment]
Thank you @cgascons, you'we most welcome! 
Thanks for reporting the issue, should be fixed now I think. 

I also changed the order of the strings simila to Google Services Gradle plugin (easier to test it produces same output) sorry if that might confuse things for you, and also added `project_id` string.

Please let me know how well it works for you. (thumbsup)

**Comment by cgascons** [comment]
Hey @dandar3, it's working like a charm now, thanks for the changes and for this magnificent tool! ;)
